import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Paper, Button, Table, TableBody, TableCell,
  TableContainer, TableHead, TableRow, IconButton, TextField,
  Dialog, DialogTitle, DialogContent, DialogActions, Grid,
  MenuItem, Chip, useTheme, useMediaQuery
} from '@mui/material';
import {
  Add as AddIcon,
  Search as SearchIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  FilterList as FilterListIcon
} from '@mui/icons-material';

interface Patient {
  id: string;
  nik: string;
  name: string;
  gender: string;
  date_of_birth: string;
}

const Patients: React.FC = () => {
  const [patients, setPatients] = useState<Patient[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [open, setOpen] = useState(false);
  const [newPatient, setNewPatient] = useState<Partial<Patient>>({
    name: '',
    nik: '',
    gender: 'Male',
    date_of_birth: ''
  });

  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  useEffect(() => {
    fetchPatients();
  }, []);

  const fetchPatients = async () => {
    try {
      const response = await fetch('http://localhost:8080/api/v1/patients/');
      const data = await response.json();
      setPatients(data.patients || []);
    } catch (err) {
      console.error('Failed to fetch patients:', err);
    }
  };

  const handleAddPatient = async () => {
    try {
      const response = await fetch('http://localhost:8080/api/v1/patients/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            ...newPatient,
            // ID will be generated by DB (UUID)
        }),
      });
      if (response.ok) {
        fetchPatients();
        setOpen(false);
        setNewPatient({ name: '', nik: '', gender: 'Male', date_of_birth: '' });
      }
    } catch (err) {
      console.error('Failed to add patient:', err);
    }
  };

  const filteredPatients = patients.filter(p =>
    p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.nik.includes(searchTerm)
  );

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4, flexWrap: 'wrap', gap: 2 }}>
        <Typography variant="h4" sx={{ fontWeight: 'bold' }}>Data Pasien</Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => setOpen(true)}
          sx={{ borderRadius: 2, px: 3 }}
        >
          Tambah Pasien
        </Button>
      </Box>

      <Paper sx={{ p: 2, mb: 3, borderRadius: 4, display: 'flex', gap: 2, alignItems: 'center' }}>
        <SearchIcon color="action" />
        <TextField
          placeholder="Cari Nama atau NIK..."
          variant="standard"
          fullWidth
          InputProps={{ disableUnderline: true }}
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
        <IconButton>
          <FilterListIcon />
        </IconButton>
      </Paper>

      <TableContainer component={Paper} sx={{ borderRadius: 4, boxShadow: '0 4px 20px rgba(0,0,0,0.05)' }}>
        <Table>
          <TableHead sx={{ bgcolor: 'rgba(0,0,0,0.02)' }}>
            <TableRow>
              <TableCell>Nama Lengkap</TableCell>
              <TableCell>NIK</TableCell>
              {!isMobile && <TableCell>Jenis Kelamin</TableCell>}
              {!isMobile && <TableCell>Tanggal Lahir</TableCell>}
              <TableCell align="right">Aksi</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {filteredPatients.map((patient) => (
              <TableRow key={patient.nik} hover>
                <TableCell sx={{ fontWeight: 'bold' }}>{patient.name}</TableCell>
                <TableCell>{patient.nik}</TableCell>
                {!isMobile && (
                  <TableCell>
                    <Chip
                      label={patient.gender}
                      size="small"
                      variant="outlined"
                      color={patient.gender === 'Male' ? 'primary' : 'secondary'}
                    />
                  </TableCell>
                )}
                {!isMobile && <TableCell>{patient.date_of_birth || '-'}</TableCell>}
                <TableCell align="right">
                  <IconButton size="small" color="primary"><EditIcon fontSize="small" /></IconButton>
                  <IconButton size="small" color="error"><DeleteIcon fontSize="small" /></IconButton>
                </TableCell>
              </TableRow>
            ))}
            {filteredPatients.length === 0 && (
              <TableRow>
                <TableCell colSpan={isMobile ? 3 : 5} align="center" sx={{ py: 3, opacity: 0.5 }}>
                  Belum ada data pasien.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </TableContainer>

      <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm" PaperProps={{ sx: { borderRadius: 4 } }}>
        <DialogTitle sx={{ fontWeight: 'bold' }}>Tambah Pasien Baru</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12}>
              <TextField
                label="Nama Lengkap"
                fullWidth
                value={newPatient.name}
                onChange={(e) => setNewPatient({...newPatient, name: e.target.value})}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                label="NIK"
                fullWidth
                value={newPatient.nik}
                onChange={(e) => setNewPatient({...newPatient, nik: e.target.value})}
              />
            </Grid>
            <Grid item xs={12} sm={6}>
              <TextField
                select
                label="Jenis Kelamin"
                fullWidth
                value={newPatient.gender}
                onChange={(e) => setNewPatient({...newPatient, gender: e.target.value})}
              >
                <MenuItem value="Male">Laki-laki</MenuItem>
                <MenuItem value="Female">Perempuan</MenuItem>
              </TextField>
            </Grid>
            <Grid item xs={12}>
              <TextField
                label="Tanggal Lahir"
                type="date"
                fullWidth
                InputLabelProps={{ shrink: true }}
                value={newPatient.date_of_birth}
                onChange={(e) => setNewPatient({...newPatient, date_of_birth: e.target.value})}
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions sx={{ p: 3 }}>
          <Button onClick={() => setOpen(false)} color="inherit">Batal</Button>
          <Button onClick={handleAddPatient} variant="contained" sx={{ px: 4 }}>Simpan</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default Patients;
